### ISSUE TITLE
XMI File Support

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#7]
We have two choices here:
* Use Chris's beta patch and work on that until it works
* Use a C version of Thirdeye's implimentation

Either way, we should validate against Thirdeye's music reproduction.

**Comment by psi29a** [comment]
Need to think about this...

**Comment by psi29a** [comment]
So we have xmi support, but it could be fixed up with extra features. I'll break this ticket off into sub-tickets for 0.4.1 (or later).

**Comment by chrisisonwildcode** [comment]
Yes, go for it .. break it off into a TODO for 0.4.1 ... i.e.: xmi playback does not adhere to conversion options.

**Comment by psi29a** [comment]
Not sure if relevant, but this xmi sounds off on your branch in comparison to master. The result of your branch yields output that is slow... (double the length).

I'll email it to everyone. Don't have dropbox handy at the moment.

**Comment by psi29a** [comment]
Email sent.

**Comment by chrisisonwildcode** [comment]
Have you got the latest branch ... all 3 xmi's you sent me succeed on my end ...

Testing: /Users/chrisisonwildcode/Downloads/xmi 2/INTROTHM1.XMI
Success

Testing: /Users/chrisisonwildcode/Downloads/xmi 2/INTROTHM2.XMI
Success

Testing: /Users/chrisisonwildcode/Downloads/xmi 2/TITLOOP.XMI
Success

**Comment by chrisisonwildcode** [comment]
my bad, email I was reading was old ...

**Comment by chrisisonwildcode** [comment]
I don't think I received the email from you ...

**Comment by chrisisonwildcode** [comment]
Ok. looks like xmi does only look at first tempo ... the 2nd tempo in that xmi is slower than the first one ... and slower than the theme I heard on youtube from a gameplay video.

**Comment by chrisisonwildcode** [comment]
try it now

**Comment by psi29a** [comment]
master branch:
<pre>
Playing 1.FSEQ 
q       [Approx  1m 59s Total]
</pre>

latest wildcode-updates:
<pre>
Playing 1.FSEQ 
q       [Approx  2m 36s Total]
</pre>

still doesn't sound quite right...

sending new dump via email

**Comment by chrisisonwildcode** [comment]
Please note that master branch has the bug that ignored some samples until next midi event making the play time shorter than it should of been. Both midi files are the same length (in time) in Logic Pro 9 & X

**Comment by chrisisonwildcode** [comment]
I should also add that 0.3 had the same bug

**Comment by psi29a** [comment]
Ah! Great catch, that. :)
I think the sound is off because you currently don't do any conversions while master did mt32 to GM. I'll test tomorrow morning and if it tests out alright, I'll close this.

**Comment by sezero** [comment]
On 1/3/15, chrisisonwildcode <notifications@github.com> wrote:
> I should also add that 0.3 had the same bug
>

Do you have a (minimal) patch for 0.3 ?

**Comment by psi29a** [comment]
OK... listening to the 1.fseq in its entirety. The track says it is 2m 36s long, but around 2m the song ends and it is just silence for 36s.   Is that normal?  This doesn't happen in master.

**Comment by psi29a** [comment]
[Approx  1m 59s Total] [   ] [100] [ 1m 59s Processed] [100%] <-- that is the length of the track as I hear it on master.  (like noted above)

**Comment by chrisisonwildcode** [comment]
I will look into this, trying to work out how changed to gauss made it into my branch and not master, specially since I didn't touch it ...

**Comment by chrisisonwildcode** [comment]
Try now :)

**Comment by psi29a** [comment]
Not noticing a difference, still has 37s of silence difference then how it is in master.

What is exactly is the difference between how Ryan and I implemented XMI support and how you did?

I wish I could look deeper, but I have 3 children that need me. ;)

I'll have more time once they are back at school.

**Comment by chrisisonwildcode** [comment]
devtest and a hexdump  on 1.FSEQ.xmi show a lot of events after the last note off. If I added up all the intervals and did the math I bet its about 37sec worth ... want me to add skipping silence at the end  to the -s command line .... ?

On a sort of related note I need to add controller names to devtest output and maybe a time thingy too.

**Comment by psi29a** [comment]
OK, I just got to listen to them via my headphones at work.  There is a big difference in how the files sound between master and updates-branch, which has nothing to do with conversions as the master branch defaults to -g0 (default: no conversion).

Here is the dump of Eye of the Beholder 3, including adlib, pc-speaker and mt-32 versions of the same xmi file.

For example, take Originals/mt-32/LICH 00001.xmi and play back with master branch build, the notes hit hard and drop softly off. It also runs for about 21s.  On the wildcode-updates branch, the note holds then lets go, no fadding. It also runs for 31s. 

Similar is DARK 00001.xmi, master branch has the notes fadding in (like an intro scene) and lasts about 25s (though sounds cut off at the end), but the wildcode-updates is just full on blast of each node.

If you want, I can dump to wave... but you can do it as well. I consider how it sounds in the master branch to be superior and would consider that the default sound we are aiming for.

**Comment by psi29a** [comment]
https://dl.dropboxusercontent.com/u/396161/EYE3.tar.bz2
^-- EYE3 dumps

**Comment by chrisisonwildcode** [comment]
I am looking into issues mentioned here. 

Problem: Master has shorter playing times than Devtest.
Answer: Master still contains a bug that skipped some "samples till next" making the overall playing time faster. Devtest shows that -updates has the same time for the XMI playback, the "m" midi, and the -x converter

**Comment by chrisisonwildcode** [comment]
Problem: LICH 00001.xmi not fading in
Answer: When I re-wrote the volume code I thing a part of my brain went on holiday. Code did not match how it was meant to work. Fixed now.

I am still working on trying to figure out why the master instruments decay better ...

**Comment by chrisisonwildcode** [comment]
ok, I think something got lost when part of the code was re-written/optimised/etc ... 

Anyways please test -updates now ...

**Comment by psi29a** [comment]
OK, I'll give it a look/ear when I get the chance. :)

**Comment by psi29a** [comment]
I had a listen: LICH 00001.xmi

It still doesn't sound right... same notes are being played at the right time. But the decay or fading out isn't happening.

My original xmi2midi does a dump of: 2576 bytes.
Current master does a dump of: 2601 bytes

https://dl.dropboxusercontent.com/u/396161/LICH_old_master.mid
https://dl.dropboxusercontent.com/u/396161/LICH_new_master.mid

Now I played the old_master.mid back on the new_master branch wildmidi binary... and it doesn't do any fading/decaying. Weird, so I played back the new_master.mid with the old_master wildmidi and it plays just fine.

It looks like it has nothing to do with the XMI conversion, but how the midi files are being played back.

Is this possibly related to this ticket https://github.com/Mindwerks/wildmidi/issues/84 ?

**Comment by psi29a** [comment]
Otherwise, I consider this issue closed and that we fix #84 before releasing 0.4.0. What do you think?

**Comment by sezero** [comment]
On 2/5/15, Bret Curtis <notifications@github.com> wrote:
[...]
> It looks like it has nothing to do with the XMI conversion, but how the midi
> files are being played back.

I believe the generated midi also sounds fine with current 0.3.8??
Current master sounds worse than 'old master' or wildmidi-0.3 and
there are issues of extra silence added to start at playback too..

**Comment by psi29a** [comment]
I agree, three issues here... not XMI related.

1) extra silence added to start of playback
2) extra silence added to end of playback
3) sounds "worse" than than wildmidi-0.3 branch

**Comment by chrisisonwildcode** [comment]
While I will check again for anything being added accidentally that's adding silence I will point out that a lot of the xmi's I have tested that play with extra silence at the end have the extra silence within them after the last note off.

What I can do if you would like it is modify the command line that skips starting silence to remove silence from either end of the song. Thoughts?

**Comment by psi29a** [comment]
That would give us something to work with in 1) and 2).

How about the 3) case? The decay/fade issue?

**Comment by chrisisonwildcode** [comment]
I'll have to do some extreme debugging to work out what's going on. It's either a bug in earlier versions, or something got mucked up somewhere.

Or it could be I fixed it but didn't commit because I was still testing then forgot about it in the push to get the formats done. 

Either way I will pin down what's going on then let you guys know.

**Comment by chrisisonwildcode** [comment]
Please test out the Find_Out_Whats_Up_With_Sample_Release branch and it this is no longer an issue please close this and merge the branch.

Just so you know what I did to fix it:

Testing was done by displaying output of the resampler of both the 0.3.8 branch and the 0.4 master branch. This output was then compared and it was noted that 0.3.8 was using sustained release for samples with the sustain flag set while 0.4 branch was not. This has since been fixed in the 0.4 branch.

Once this one is tested and closed I will be doing the fix for too much silence at beginning and end. I wish to reassure you that this is not WildMidi's fault, instead the files do contain the silence. However I will modify the option to jump ahead of beginning silence to remove beginning and end silence from the playback.

**Comment by sezero** [comment]
The new branch sounds like wildmidi-0.3 branch, so no longer sounding
worse and that's good. As for the midi I tested, wildmidi-0.3 reports
that it's 2m 56s Total, whereas 0.4/new branch reports 3m  3s Total:
possibly some extra silence added?? (sent the midi file to your
personal email.)

**Comment by psi29a** [comment]
Great job @chrisisonwildcode, everything XMI related sounds good.

The extra silence we'll tackle later in another issue, since as you said, you're just following instructions.

**Comment by sezero** [comment]
Cherry-picked the single commit in the branch into master, and then
deleted the branch.
